# Generated by Django 5.0.4 on 2024-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
