# Generated by Django 5.0.6 on 2024-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pictures",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ImageField(blank=True, default="", upload_to="products"),
        ),
        migrations.DeleteModel(
            name="Picture",
        ),
    ]
