# Generated by Django 5.0.6 on 2024-06-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_product_pictures_product_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="mrp",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
