# Generated by Django 5.0.4 on 2024-07-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_rename_description_product_description1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description1",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="description2",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="description3",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="description4",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="description5",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
