# Generated by Django 5.2.4 on 2025-07-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
