# Generated by Django 5.2.4 on 2025-07-16 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_moified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
