# Generated by Django 5.0.6 on 2024-06-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_product_mrp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("sales", models.CharField(max_length=200)),
                ("banner_img", models.ImageField(upload_to="banner")),
            ],
        ),
    ]
