# Generated by Django 5.0.6 on 2024-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
