# Generated by Django 5.0.4 on 2024-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_profile_old_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="description1",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="images",
            new_name="images1",
        ),
        migrations.AddField(
            model_name="product",
            name="description2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="description3",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="description4",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="description5",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="images2",
            field=models.ImageField(blank=True, default="", upload_to="products"),
        ),
        migrations.AddField(
            model_name="product",
            name="images3",
            field=models.ImageField(blank=True, default="", upload_to="products"),
        ),
        migrations.AddField(
            model_name="product",
            name="images4",
            field=models.ImageField(blank=True, default="", upload_to="products"),
        ),
        migrations.AddField(
            model_name="product",
            name="mainDescription",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
